name: DEBUG

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
      TUNNEL_HOST: ${{secrets.TUNNEL_HOST}}
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Connect Back
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          mkdir -p /home/runner/.ssh
          cat <<< ${SSH_PRIVATE_KEY} > /home/runner/.ssh/id_rsa
          cat <<< ${SSH_PUBKEY} > /home/runner/.ssh/authorized_keys
          chmod 600 /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/authorized_keys
          chmod 700 /home/runner/.ssh
          random_port=$(shuf -i 20000-65000 -n 1)
          if [[ -n "${TELEGRAM_BOT_TOKEN}" && -n "${TELEGRAM_CHAT_ID}" ]]; then
              TELEGRAM_LOG="/tmp/telegram.log"
              SSH_CMD="ssh runner@127.0.0.1 -p $random_port"
              MSG="
              *GitHub Actions - 云编译_X64 SSH tunnel info:*
              ⚡ *CLI:*
              \`${SSH_CMD}\`
              "
              echo -e "Sending message to Telegram..."
              curl -sSX POST "${TELEGRAM_API_URL:-https://api.telegram.org}/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                  -d "disable_web_page_preview=true" \
                  -d "parse_mode=Markdown" \
                  -d "chat_id=${TELEGRAM_CHAT_ID}" \
                  -d "text=${MSG}" >${TELEGRAM_LOG}
              TELEGRAM_STATUS=$(cat ${TELEGRAM_LOG} | jq -r .ok)
              if [[ ${TELEGRAM_STATUS} != true ]]; then
                  echo -e "Telegram message sending failed: $(cat ${TELEGRAM_LOG})"
              else
                  echo -e "Telegram message sent successfully!"
              fi
          fi
          screen -dmS ngrok bash -c \
              "ssh -CNTR $random_port:127.0.0.1:22 -oStrictHostKeyChecking=no -oServerAliveInterval=30 -oServerAliveCountMax=60 -C root@${TUNNEL_HOST} -v 2>&1"
      - name: SSH 连接到 Actions
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
