name: DEBUG

on:
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 保存编译环境
        run: |
          cd
          echo "${{ secrets.GITHUB_TOKEN }}" >> debugenv
      - name: SSH 连接到 Actions
        uses: P3TERX/ssh2actions@main
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
