name: 云编译_MT7620A_CACHED

on:
  workflow_dispatch:
    inputs:
      commit:
        default: 'master'
        description: 'which commit should be build'
  schedule:
    - cron: 0 0 1 * *

jobs:
  build:
    name: 云编译
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_PUBKEY: ${{secrets.SSH_PUBKEY}}
      TUNNEL_HOST: ${{secrets.TUNNEL_HOST}}
      DEVICE: mt7620a
    if: github.event.repository.owner.id == github.event.sender.id || ! github.event.sender.id

    steps:
      - name: 清理空间
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          mkdir -p /home/runner/.ssh
          cat <<< ${SSH_PRIVATE_KEY} > /home/runner/.ssh/id_rsa
          cat <<< ${SSH_PUBKEY} > /home/runner/.ssh/authorized_keys
          chmod 600 /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/authorized_keys
          chmod 700 /home/runner/.ssh
          random_port=$(shuf -i 20000-65000 -n 1)
          if [[ -n "${TELEGRAM_BOT_TOKEN}" && -n "${TELEGRAM_CHAT_ID}" ]]; then
              TELEGRAM_LOG="/tmp/telegram.log"
              SSH_CMD="ssh runner@127.0.0.1 -p $random_port"
              MSG="
              *GitHub Actions - 云编译_MT7620A SSH tunnel info:*
              ⚡ *CLI:*
              \`${SSH_CMD}\`
              "
              echo -e "Sending message to Telegram..."
              curl -sSX POST "${TELEGRAM_API_URL:-https://api.telegram.org}/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
                  -d "disable_web_page_preview=true" \
                  -d "parse_mode=Markdown" \
                  -d "chat_id=${TELEGRAM_CHAT_ID}" \
                  -d "text=${MSG}" >${TELEGRAM_LOG}
              TELEGRAM_STATUS=$(cat ${TELEGRAM_LOG} | jq -r .ok)
              if [[ ${TELEGRAM_STATUS} != true ]]; then
                  echo -e "Telegram message sending failed: $(cat ${TELEGRAM_LOG})"
              else
                  echo -e "Telegram message sent successfully!"
              fi
          fi
          screen -dmS ngrok bash -c \
              "ssh -CNTR $random_port:127.0.0.1:22 -oStrictHostKeyChecking=no -oServerAliveInterval=30 -oServerAliveCountMax=60 -C root@${TUNNEL_HOST} -v 2>&1"
          nohup sh -c '
          sudo -E apt update
          sudo -E apt -y install adduser antlr3 asciidoc autoconf automake autopoint binutils build-essential bzip2 ccache cmake curl device-tree-compiler flex g++-multilib gawk gcc-multilib gettext git git-core gperf haveged intltool jq htop lib32gcc1 libc6-dev-i386 libelf-dev libglib2.0-dev libncurses5-dev libreadline-dev libssl-dev libtool libz-dev lrzsz mkisofs man msmtp net-tools netstat-nat p7zip p7zip-full patch perl pv python-ply python2.7 python3 python3-pip python3-ply qemu-utils rsync scons screen subversion sudo swig tar texinfo uglifyjs unzip upx uuid-runtime vim w3m wget xmlto zlib1g-dev
          sudo rm -rf \
            /usr/share/dotnet \
            /etc/mysql \
            /etc/php
          sudo -E apt-get -y purge \
            azure-cli \
            ghc* \
            zulu* \
            hhvm \
            llvm* \
            firefox \
            google* \
            dotnet* \
            powershell \
            openjdk* \
            mysql* \
            php*
            sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
            sudo sysctl vm.swappiness=0
            docker rmi -f `docker images -q`
            ' &
      - name: 恢复编译环境
        run: |
          cd
          curl -sL https://raw.githubusercontent.com/klever1988/nanopi-openwrt/zstd-bin/zstd | sudo tee /usr/bin/zstd > /dev/null
          for i in {1..10}
          do
            curl -sL --fail https://github.com/tofuliang/lede/releases/download/cache/lede.$DEVICE.img.zst.0$i || break
          done | zstdmt -d -o lede.img || (truncate -s 30g lede.img && mkfs.btrfs -M lede.img)
          LOOP_DEVICE=$(losetup -f) && echo "LOOP_DEVICE=$LOOP_DEVICE" >> $GITHUB_ENV
          sudo losetup -P --direct-io $LOOP_DEVICE lede.img
          mkdir lede && sudo mount -o nossd,compress=zstd $LOOP_DEVICE lede
          if [ -d 'lede/.git' ]; then
            cd lede && rm -f zerospace && git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
            git fetch && git reset --hard origin/master
            if [ "q${{ github.event.inputs.commit }}" != "q" ] && [ "q${{ github.event.inputs.commit }}" != "qmaster" ] ; then
              tar cvf ~/rebase.tar .github/workflows/debug.yaml .github/workflows/fastbuild-* .github/workflows/merge-upstream.yaml \
              .github/workflows/openwrt-ci_vssr.yaml .gitpod.yml Openwrtfile build_profile.sh debugInit.sh homerouter.config \
              homerouter_files.txz k1.config lenovo_newifi-y1.config prebuild.sh yk-l1.config yk-l1-printer.config yk-l1c.config \
              autocore.patch0 luci.patch0 xxd-1.10.tar.gz && git reset --hard ${{ github.event.inputs.commit }} && tar xvf ~/rebase.tar
            fi
          else
            sudo chown $USER:$(id -gn) lede && git clone -b master --single-branch https://github.com/tofuliang/lede lede
          fi
      - name: 编译准备工作
        run: |
          echo "默认工作路径：$(pwd)"
          cd ~/lede
          ./prebuild.sh
          df -h .
      - name: 编译固件
        run: |
          cd ~/lede
          bash build_profile.sh k1
          echo -e "$(nproc) thread build k1 ."
          make -j$(nproc) || make -j1 || make -j1 V=sc
          mv bin/targets/ramips/mt7620/config.buildinfo bin/targets/ramips/mt7620/config.buildinfo.k1
          bash build_profile.sh yk-l1
          echo -e "$(nproc) thread build yk-l1 ."
          make -j$(nproc) || make -j1 || make -j1 V=sc
          mv bin/targets/ramips/mt7620/config.buildinfo bin/targets/ramips/mt7620/config.buildinfo.yk-l1
          bash build_profile.sh yk-l1c
          echo -e "$(nproc) thread build yk-l1c ."
          make -j$(nproc) || make -j1 || make -j1 V=sc
          mv bin/targets/ramips/mt7620/config.buildinfo bin/targets/ramips/mt7620/config.buildinfo.yk-l1c
          bash build_profile.sh lenovo_newifi-y1
          echo -e "$(nproc) thread build lenovo_newifi-y1 ."
          make -j$(nproc) || make -j1 || make -j1 V=sc
          mv bin/targets/ramips/mt7620/config.buildinfo bin/targets/ramips/mt7620/config.buildinfo.lenovo_newifi-y1
          bash build_profile.sh yk-l1-printer printer
          echo -e "$(nproc) thread build yk-l1-printer ."
          make -j$(nproc) || make -j1 || make -j1 V=sc
          mv bin/targets/ramips/mt7620/config.buildinfo bin/targets/ramips/mt7620/config.buildinfo.yk-l1-printer          
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin
      - name: 上传资源
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_artifact
          path: ~/lede/bin
      - name: 设置版本号
        run: |
          cd ~/lede
          echo "ReleaseVersion=$(date +%Y.%m.%d)-$(git rev-parse --short HEAD^)" >> $GITHUB_ENV
      - name: 整理Release文件
        run: |
          rm -rf ./artifact/

          mkdir -p ./artifact/firmware
          find ~/lede/bin/targets/ -name "*mt7620*bin" | xargs -i mv -f {} ./artifact/firmware/
          (cd ./artifact/firmware/;[ `ls|grep .bin|wc -l` -gt 0 ] && tar cJf [$(date +%Y%m%d)]openwrt-firmware_$DEVICE.txz *.bin && rm *.bin)

          mkdir -p ./artifact/package
          mv -f $(find ~/lede/bin/packages/ -type f -name "*.ipk") ./artifact/package/
          (cd ./artifact/package/;tar cJf package_$DEVICE.txz *.ipk && rm *.ipk)

          mkdir -p ./artifact/buildinfo
          mv -f $(find ~/lede/bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest" -o -name "config.seed") ./artifact/buildinfo/
          (cd ./artifact/buildinfo/;tar cJf ../buildinfo_$DEVICE.txz * && rm -fr ./* && mv ../buildinfo_$DEVICE.txz ./ ;)
      - name: 发布Release
        uses: 'marvinpinto/action-automatic-releases@latest'
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          prerelease: false
          automatic_release_tag: ${{ env.ReleaseVersion }}-${{ env.DEVICE }}
          title: ${{ env.ReleaseVersion }}-${{ env.DEVICE }}
          files: |
            ./artifact/buildinfo/*
            ./artifact/package/*
            ./artifact/firmware/*
      - name: 保存编译环境
        run: |
          rm -fr ~/lede/bin
          cd ~/lede
          [ "0$(df -h|grep 'runner/lede'|awk '{print $5}'|grep -oE '[0-9]+')" -gt 50 ] && make package/clean && rm -fr dl
          cd
          sleep 60
          sudo mount -o remount,compress=no,nodatacow,nodatasum lede
          cd lede/; pv /dev/zero > zerospace || true; sync; rm -f zerospace; cd -
          sleep 60
          sudo umount lede
          sudo losetup -d $LOOP_DEVICE
          export AUTH="Authorization: Token ${{ secrets.GITHUB_TOKEN }}"
          export cache_path='github.com/repos/tofuliang/lede/releases'
          export cache_repo_id='51364999'
          ret=$(curl -sH "$AUTH" "https://api.$cache_path/tags/cache")
          echo $ret | jq -r '.assets[] | select(.name | contains ("'$DEVICE'.img")).id' | \
          xargs -n1 -i curl -X DELETE -H "$AUTH" "https://api.$cache_path/assets/{}"
          #zstdmt -c --adapt --long lede.img | parallel --wc --block 1.99G --pipe \
          #'curl -s --data-binary @- -H "$AUTH" -H "Content-Type: application/octet-stream" https://uploads.$cache_path/$cache_repo_id/assets?name=lede.'$DEVICE'.img.zst.0{#} > /dev/null'
          zstdmt -c --long lede.img | split --numeric=1 -b 2000m - lede.$DEVICE.img.zst.
          #for f in *img.zst*
          #do
          #  while true; do curl --data-binary @$f -H "$AUTH" -H 'Content-Type: application/octet-stream' "https://uploads.$cache_path/$cache_repo_id/assets?name=$f" && break || true; done
          #done
          ls *img.zst* | parallel --wc 'while true; do curl -T {} -H "$AUTH" -H "Content-Type: application/octet-stream" "https://uploads.$cache_path/$cache_repo_id/assets?name={}" && break || true; done'
      - name: 发送telegram通知
        run: |
          curl -k --data chat_id="${{secrets.TELEGRAM_CHAT_ID}}" --data "text=The ${{env.DEVICE}} build ran completed at ${{job.status}}." "https://api.telegram.org/bot${{secrets.TELEGRAM_BOT_TOKEN}}/sendMessage"
      - name: 失败调试
        uses: P3TERX/ssh2actions@main
        if: ${{ failure() }}
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
